### ISSUE TITLE
"message": "Could not instantiate CPSign: Missing required parameter 'license'"

### ISSUE THREAD

**Issue by WangYitian123** [pharmbio/cplogd#4]
Hi,I meet the error of "message": "Could not instantiate CPSign: Missing required parameter 'license'". 
Could you please help me?
Thanks a lot.

**Comment by WangYitian123** [comment]
![image-20220902101401576](../Library/Application%20Support/typora-user-images/image-20220902101401576.png)
In detail, when I run the command man clean package jetty:run, it occurred.

**Comment by WangYitian123** [comment]
In detail, when I run the command man clean package jetty:run, it occurred.
![image-20220902101401576](../Library/Application%20Support/typora-user-images/image-20220902101401576.png)

**Comment by WangYitian123** [comment]
Or would you please give me a way to use your products, especially for smiles, not only a smile?
The website https://cplogd.service.pharmb.io/draw/ cannot be used now.

**Comment by jonalv** [comment]
Have a look at 
https://predgui.serve.scilifelab.se/
and
https://predguimm.serve.scilifelab.se/

**Comment by WangYitian123** [comment]
It worked. But how can I download the multiple results?
https://predguimm.serve.scilifelab.se/ only shows the results, but I cannot find the download tools.
Would you please help me?
Thanks a lot.

**Comment by jonalv** [comment]
I don't think we currently have the feature to download it as csv file no. Should probably be added at some point

**Comment by WangYitian123** [comment]
Hi,https://predguimm.serve.scilifelab.se/ now cannot show the predicted results in cplogd model. Could you plesae help me?

**Comment by jonalv** [comment]
Maybe, what did you do? :)

How can I reproduce your error?

// Jonathan

**Comment by WangYitian123** [comment]
open the https://predguimm.serve.scilifelab.se/, and choose the cplogd model,submit any file , the results would apper [undifined,undifined]

**Comment by jonalv** [comment]
Strange, I will check with some colleagues and get back to you.
// Jonathan

**Comment by WangYitian123** [comment]
Thanks a lot.

**Comment by WangYitian123** [comment]
Thanks a lot. I cannot wait to use it. :)

**Comment by jonalv** [comment]
Sorry for late answer. It seems to be working now
